### ISSUE TITLE
what the "capture size" means?

### ISSUE THREAD

**Issue by ericyan71** [brilee/MuGo#10]
I read your paper, I don't understand Capture Size, if at state S(t), we get a result A(t), is the Capture size the result of the move A(t) ? or the result of move A(t-1)?  and about liberties after move, is it the same as capture size? thanks.

**Comment by brilee** [comment]
(Not my paper - DeepMind's paper!)

The capture size is the result of the move, yes. So if playing at a certain location would trigger a capture of N stones, then the "stones captured" feature plane gets a 1 on that particular location, on the Nth one-hot encoded plane.

**Comment by brilee** [comment]
Happy to answer any other questions.

**Comment by Mysayal** [comment]
What does feature "Ones" and "Zeroes" mean?
You said it makes NN know the bound of the board, I still can not understand...
Thanks. @brilee

**Comment by brilee** [comment]
I wrote up a short description of that feature here  http://moderndescartes.com/essays/convnet_edge_detection - let me know if that helps or if you still have questions.
