### ISSUE TITLE
What hardware i need to build and develop Mugo.

### ISSUE THREAD

**Issue by Godady** [brilee/MuGo#12]
It's exciting to get MuGo(a personal Alphago) in PCs. Thank your work!  I'm interested in your work. I have a pc with Intel I5-4590, 8GB ram, GTX770(1253 cudas).  And i have tens of thousand professional SGFs ready to be training. If I want to train 100,000 SGFs with my hardware using Mugo, how long i need training. I learned for Deep Learning hardware GPU is more important than CPUs and High cpu frequency is more important than multi-threads and cores cpu has, is it right? Please give me some advice about hardware configuration. Thank you!

**Comment by brilee** [comment]
That sounds like a good enough setup. I'm using a GTX 960 w/ 4GB ram. My training times have been about 1day per epoch (1 epoch being 1 pass through my 100,000 SGFs), and I'm not yet augmenting my data by doing all 8 reflections/rotations. My observation is that prediction rate still goes up very slowly after 3-4 days, but it plays okay after just 1.
