### ISSUE TITLE
Training failed, has no attribute 'mul'

### ISSUE THREAD

**Issue by penguincwarrior** [brilee/MuGo#18]
(tf3.4) cong@jsjc-PowerEdge-T630:~/Downloads/MuGo$ python main.py train processed_data --save-file=tmp/savedmodel1 --epochs=1 --logdir=logs/my_training_run
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    argh.dispatch(parser)
  File "/home/cong/anaconda3/envs/tf3.4/lib/python3.4/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/cong/anaconda3/envs/tf3.4/lib/python3.4/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/cong/anaconda3/envs/tf3.4/lib/python3.4/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "main.py", line 72, in train
    n = PolicyNetwork()
  File "/home/cong/Downloads/MuGo/policy.py", line 49, in __init__
    self.set_up_network()
  File "/home/cong/Downloads/MuGo/policy.py", line 90, in set_up_network
    log_likelihood_cost = -tf.reduce_mean(tf.reduce_sum(tf.mul(tf.log(output), y), reduction_indices=[1]))
AttributeError: 'module' object has no attribute 'mul'

I am sure that preprocessing work is done, and trunk files are stored at processed_data.
I use ubuntu 14.04 LTS, anaconda environment, python3.4. argh,sfg has been in the 'conda list' result.

**Comment by mysayalHan** [comment]
I met the same problems.
You should change tf.mul into tf.multiply and it will work!

**Comment by penguincwarrior** [comment]
Yeah, I am new to both python and tensorflow, and just before I managed to know how silly the question is when you give the correct answer... Thanks mysayalHan!

**Comment by brilee** [comment]
Yep, looks like it's a tensorflow 0.12 vs. 1.0 api difference. (I had been using 0.12)
