### ISSUE TITLE
Is the rollout fastNet implemented?

### ISSUE THREAD

**Issue by joyousrabbit** [brilee/MuGo#21]
Hello, really nice work. Is the rollout fastNet implemented? I see in the code that it's simply replaced by the full policy net. Why not use a fast rollout net as said in the paper?

**Comment by brilee** [comment]
Thanks. It's not implemented; there are lots of microoptimizations involved
that would entail a lot of work. Given the nature of the project
(educational and written in Python instead of a faster language), I think
trying to implement fast rollouts would be doomed to fail.

**Comment by joyousrabbit** [comment]
Thanks reply. If we use the policynet as a heuristic guide, a MTFS is it
still suitable?
1. When expending the leaf, the MTFS dosen't keep the simulation because
it's random and will rarely meet again in future; however, the policynet
gives always the several very possible moves and most of them will be
reviewed when expending new leaf. There is much re-computation, isn't it?
2. The rootNode is set for every step, without the knowledge of last
simulations. Similar to the issue (1), do you think initialize it by
keeping the already done simulations a better way?

**Comment by brilee** [comment]
Policy net still works for MCTS, although it'll be really slow. (I clocked
a full playout as taking about 1 second, so the current implementation
might only get on the order of 10 playouts before making its move.) I was
considering parallelizing the tree search, but that would still only
increase #playouts by a factor of 10 or so. Nowhere near the 1000s of
playouts you would need to see an improvement over pure policy net.

The root node is the same, yes, but each node is mutated after each
playthrough. This is done in the `backup_value` method. The tree as a whole
grows by 1 node after each MCTS step.

**Comment by brilee** [comment]
note - I'm planning to use value network only, no rollouts.
