### ISSUE TITLE
error message "Key RL_glocal_step not found in checkpoint"

### ISSUE THREAD

**Issue by tingtinglu** [brilee/MuGo#29]
At running
python main.py gtp policy --read-file=saved_models/20170718'
it appeared the wrong message:

Key RL_glocal_step not found in checkpoint

Can someone help me? Thanks so much !

**Comment by brilee** [comment]
This is because I updated the policy network definition. You can check out `git checkout v0.1` to revert to a version consistent with the saved model.

**Comment by brilee** [comment]
I've updated README with instructions. See the section that says "If you just want to get MuGo working, you can download a pretrained network..."
