### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Key RL_global_step not found in checkpoint

### ISSUE THREAD

**Issue by ybtq** [brilee/MuGo#30]
tensorflow version: 1.3 (CPU)
When I run : python main.py gtp policy --read-file=saved_models/20170718

It causes an error:
tensorflow.python.framework.errors_impl.NotFoundError: Key RL_global_step not fo
und in checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32], _device="/job:loc
alhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names
, save/RestoreV2/shape_and_slices)]]
How to fix it.

**Comment by brilee** [comment]
I've updated README with instructions. See the section that says "If you just want to get MuGo working, you can download a pretrained network..."

**Comment by ybtq** [comment]
thanks.
