### ISSUE TITLE
SelfPlay Illegal Move

### ISSUE THREAD

**Issue by MartinDevelopment** [brilee/MuGo#31]
Traceback (most recent call last):
  File "selfplay.py", line 43, in <module>
    winners, losers = extract_moves(positions)
  File "selfplay.py", line 32, in extract_moves
    sgf_wrapper.replay_position(final_position))
  File "/home/mrmartinke/Desktop/MuGo-master/utils.py", line 67, in take_n
    return list(itertools.islice(iterable, n))
  File "/home/mrmartinke/Desktop/MuGo-master/sgf_wrapper.py", line 174, in replay_position
    pos = pos.play_move(next_move, color=color)
  File "/home/mrmartinke/Desktop/MuGo-master/go.py", line 354, in play_move
    raise IllegalMove("Move at {} is illegal: \n{}".format(c, self))
go.IllegalMove: Move at (16, 1) is illegal:

**Comment by brilee** [comment]
Was there a board position printed out after this error message? Would be helpful in diagnosing problem.

I've noticed that sometimes my code bugs out - there's a bizarre edge case that it's not catching. I thought it was bug-free because it plays through 100,000 KGS games without throwing any errors, but apparently there are still some positions that it breaks on...

**Comment by MartinDevelopment** [comment]
Mabye this will help

`Traceback (most recent call last):
  File "selfplay.py", line 43, in <module>
    winners, losers = extract_moves(positions)
  File "selfplay.py", line 32, in extract_moves
    sgf_wrapper.replay_position(final_position))
  File "/home/mrmartinke/Desktop/MuGo-master/utils.py", line 67, in take_n
    return list(itertools.islice(iterable, n))
  File "/home/mrmartinke/Desktop/MuGo-master/sgf_wrapper.py", line 174, in replay_position
    pos = pos.play_move(next_move, color=color)
  File "/home/mrmartinke/Desktop/MuGo-master/go.py", line 354, in play_move
    raise IllegalMove("Move at {} is illegal: \n{}".format(c, self))
go.IllegalMove: Move at (18, 1) is illegal: 
   A B C D E F G H J K L M N O P Q R S T   
19 . O . . . . O . . . . . . . . . . . . 19 
18 . X O . O O X O . . . . . . . O O X . 18 
17 X . X O O X X O . . . . . O O X X . . 17 
16 . . X . O X . . . . O O O X X O . X . 16 
15 . . . X O X . . . O X X X . . O O . . 15 
14 . . O X X . X . O . O . . . X X X X . 14 
13 . O O X . . . . . . . O X X O X . . . 13 
12 . O X X . . X O O O . . X . O . . . . 12 
11 . X O . . . . X X X O O X . O . . . . 11 
10 . X O . . . . . . O X O X O O X X . . 10 
 9 . O X O . . . . . O X O O X O O . X .  9 
 8 . X X X . . . X . X X X X X O . O X .  8 
 7 O X X . . . X O X . X X . X O . O X .  7 
 6 X O . . X X O O O X O O X X O . . O .  6 
 5 . O . X . . X X O . O . . . X O O O .  5 
 4 . O X X X X O X . O O X X . X . X O .  4 
 3 X O O X . O O X O . . O O X X . X X .  3 
 2 X O O X O . X O . O . . . O O O X . .  2 
 1 O<* O X . . O . O . . . . . . O . . .  1 
   A B C D E F G H J K L M N O P Q R S T   
Move: 201. Captures X: 3 O: 6

`

**Comment by MartinDevelopment** [comment]
Here is another example. It is playing a legal move, however the program sees it as an illegal move
go.IllegalMove: Move at (0, 0) is illegal: 
   A B C D E F G H J K L M N O P Q R S T   
19 . X O . X . . . . O . . . . . . . . . 19 
18 X O X X . X O O O . O X . . . . . . . 18 
17 O O O X X X X X O O X O . . . . . . . 17 
16 O . O O X X O X O X X . . O . . . . . 16 
15 X<O X X O X O O X . . . . . . . . . . 15 
14 . X X O O O X O X . . . . . . . . . . 14 
13 X . . . . O . O . . . . . . . . . . . 13 
12 . . . . . . . . . . . . . . . . . . . 12 
11 . . O . . . . . . . . . . . . . . . . 11 
10 . . . . . . . . . . . . . . . . . . . 10 
 9 . . . . . . . . . . . . . . . . . . .  9 
 8 . . . . . . . . . . . . . . . . . . .  8 
 7 . . . . . . . . . . . . . . . . . . .  7 
 6 . . . . . . . . . . . . . . . . . . .  6 
 5 . . . . . . . . . . . . . . . . . . .  5 
 4 . . X . . . . . . . . . . . . . X . .  4 
 3 . . . . . . . . . . . . . . . . . . .  3 
 2 . . . . . . . . . . . . . . . . . . .  2 
 1 . . . . . . . . . . . . . . . . . . .  1 
   A B C D E F G H J K L M N O P Q R S T   
Move: 64. Captures X: 2 O: 2

**Comment by xhw98** [comment]
i also get this ,but the latest code removed selfplay.py? 
thie illegal move died fixed?thank you!
