### ISSUE TITLE
Error when start training

### ISSUE THREAD

**Issue by freelattice** [brilee/MuGo#32]
`python main.py train processed_data/ --save-file=/tmp/savedmodel --epochs=1 --logdir=logs/my_training_run
`

![untitled](https://user-images.githubusercontent.com/18496623/31163177-0e8b0a34-a896-11e7-89da-015794cf8757.png)

**Comment by freelattice** [comment]
I tried to replace '/' with '\' but doesn't work

**Comment by MartinDevelopment** [comment]
Try to fill out the entire path that starting with C:\ and make sure the path actually exists.

**Comment by freelattice** [comment]
@MartinDevelopment 
2017-10-04 10:16:47.082397: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\framework\op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\zzlij\Desktop\MuGo0\tmp\savedmodel
![qq 20171004101725](https://user-images.githubusercontent.com/18496623/31189665-c208731a-a8ed-11e7-9c59-8b0edf7c8600.png)

**Comment by MartinDevelopment** [comment]
Do you acctually have a model in the tmp folder that is named "savedmodel", otherwise you get this error because it hasn't created a Model yet.  If you have a model that is named differently add \(Modelname)

**Comment by freelattice** [comment]
@MartinDevelopment  No I don't have any model in tmp, it's an empty folder

**Comment by MartinDevelopment** [comment]
That's why you are getting this error, just let it run and it will create the model for you wich will be named "savedmodel" with your current command

**Comment by freelattice** [comment]
Solved, thank you

**Comment by brilee** [comment]
Thanks @MartinDevelopment
