### ISSUE TITLE
Error when prepossessing Chinese   SGF

### ISSUE THREAD

**Issue by freelattice** [brilee/MuGo#33]
When there are Chinese characters in SGF, then I got an error message:

   result = function(*positional, **keywords)
  File "main.py", line 53, in preprocess
    test_dataset = DataSet.from_positions_w_context(test_chunk, is_test=True)
  File "C:\Users\xxxx\Mugo\load_data_sets.py", line 83, in from_positions_w_context
    positions, next_moves, results = zip(*positions_w_context)
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by brilee** [comment]
Same issue as https://github.com/brilee/MuGo/issues/17 - try the fix there. I don't want to commit that change, though; feels too hacky to me.
