### ISSUE TITLE
Error while prerunning it

### ISSUE THREAD

**Issue by Teruha** [brilee/MuGo#37]
[del]I did install things included in the 'requirements.txt'.
But it seems didn't work when I commanded 'python main.py gtp policy --read-file=saved_models/20170718'.

File "main.py", line 44
    def preprocess(*data_sets, processed_dir="processed_data"):
                                           ^
The '^' is pointing to the last letter of 'processed_dir'.
SyntaxError: invalid syntax

I tried to solve it but just not worked.
And need your help.

Thanks.[/del]

It's okay. I solved it.
Marvellous work. Thanks again.

**Comment by brilee** [comment]
(For other people with same issue - this is because you need to run with python3
