### ISSUE TITLE
AttributeError: module 'go' has no attribute 'is_reasonable'

### ISSUE THREAD

**Issue by renruyi** [brilee/MuGo#6]
go.is_reasonable(position, move) is called on line 95, strategies.py
However, is_reasonable is not implemented in go.py

**Comment by renruyi** [comment]
is_reasonable is implemented on line 25. changed to is_reasonable(position, move) and it works well.

**Comment by brilee** [comment]
fixed https://github.com/brilee/MuGo/commit/af76e633cfba1cf4dfd6bf1bb4ea8301334cc6f6
