### ISSUE TITLE
preprocess error: Invalid syntax

### ISSUE THREAD

**Issue by richardxiong** [brilee/MuGo#7]
Hello,

I downloaded the kgs to the directory ./data, and call the command:
python main.py preprocess ./data/*
Then I have the error:
File "main.py", line 42
    def preprocess(*data_sets, processed_dir="./processed_data"):
                                                                          ^
SyntaxError: invalid syntax

It seems there is something wrong with the directory parsing (it doesn't work whether or not I add './' in front of 'processed_data'). Does anyone how to fix it? Thanks!

**Comment by renruyi** [comment]
I did
`python main.py preprocess data`
on my windows machine yesterday. I didn't try it on linux because my go gui programs are all on windows. Let me know if that works on linux

**Comment by T1h0can** [comment]
I have the same problem on ubuntu 16.04 , when i run: python main.py preprocess data/my-sgf/
File "main.py", line 42
    def preprocess(*data_sets, processed_dir="processed_data"):
                                           ^
SyntaxError: invalid syntax

**Comment by brilee** [comment]
This is a python3 syntax feature.
